### ISSUE TITLE
Erg file format.

### ISSUE THREAD

**Issue by delormej** [delormej/xert-convert#1]
Add a module that outputs Erg file format.

**Comment by delormej** [comment]
Initial implementation done, but no workout step comments added yet.

**Comment by dhague** [comment]
Unfortunately the rest intervals do not appear to be written out.
For example, with workout https://www.xertonline.com/workout/lWe8oLqZWp6ONTfJ the actual 20 minute SST intervals (the rest part of step 3) are not written out.

**Comment by delormej** [comment]
Thanks, I'll take a look at this tonight.

```
  From: Darren Hague <notifications@github.com>
```

 To: delormej/xert-convert xert-convert@noreply.github.com 
Cc: delormej jjdelorme@yahoo.com
 Sent: Monday, March 14, 2016 12:20 PM
 Subject: Re: [xert-convert] Erg file format. (#1)

Unfortunately the rest intervals do not appear to be written out.
For example, with workout https://www.xertonline.com/workout/lWe8oLqZWp6ONTfJ the actual 20 minute SST intervals (the rest part of step 3) are not written out.—

**Comment by delormej** [comment]
Hi Darren, can you please try again - I identified the issue and made a fix.  Thanks.

**Comment by dhague** [comment]
Looks much better, thanks!

One more small issue: when I specify the "-e" or "--erg" options on the command line the TCX content is still emitted, albeit with the ERG content appended to it.

**Comment by delormej** [comment]
Just fixed that.  Default output is now erg, alternatively you can specify -o tcx and it will exclusively output one of tcx or erg.

```
  From: Darren Hague <notifications@github.com>
```

 To: delormej/xert-convert xert-convert@noreply.github.com 
Cc: delormej jjdelorme@yahoo.com
 Sent: Tuesday, March 15, 2016 7:13 AM
 Subject: Re: [xert-convert] Erg file format. (#1)

Looks much better, thanks!One more small issue: when I specify the "-e" or "--erg" options on the command line the TCX content is still emitted, albeit with the ERG content appended to it.—
